name: Sincronizar para Perfil Pessoal

on:
  push:
    branches:
      - main

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Mirror para o meu perfil
        env:
          MINHA_CHAVE: ${{ secrets.MINHA_CHAVE_PESSOAL }}
        run: |
          
          git config --global user.email "francisco@exemplo.com"
          git config --global user.name "Francisco Santos"
          
          
          REMOTE_URL="https://x-access-token:${MINHA_CHAVE}@github.com/FranciscoMofreitaSantos/PortLogistics_ISEP.git"
          
          git push --force --prune $REMOTE_URL "refs/remotes/origin/*:refs/heads/*"